const AIRPORT_CATALOG = Object.freeze([
  Object.freeze({
    id: 'YYZ',
    iata: 'YYZ',
    name: 'Toronto Pearson International Airport',
    city: 'Toronto',
    country: 'Canada',
    lat: 43.6777,
    lng: -79.6248,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'ATL',
    iata: 'ATL',
    name: 'Hartsfield-Jackson Atlanta International Airport',
    city: 'Atlanta',
    country: 'United States',
    lat: 33.6407,
    lng: -84.4277,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'ANC',
    iata: 'ANC',
    name: 'Ted Stevens Anchorage International Airport',
    city: 'Anchorage',
    country: 'United States',
    lat: 61.1743,
    lng: -149.9985,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'BHM',
    iata: 'BHM',
    name: 'Birmingham-Shuttlesworth International Airport',
    city: 'Birmingham',
    country: 'United States',
    lat: 33.5629,
    lng: -86.7535,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'BIL',
    iata: 'BIL',
    name: 'Billings Logan International Airport',
    city: 'Billings',
    country: 'United States',
    lat: 45.8077,
    lng: -108.5429,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'BDL',
    iata: 'BDL',
    name: 'Bradley International Airport',
    city: 'Hartford',
    country: 'United States',
    lat: 41.9389,
    lng: -72.6832,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'BOI',
    iata: 'BOI',
    name: 'Boise Airport',
    city: 'Boise',
    country: 'United States',
    lat: 43.5644,
    lng: -116.2228,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'BOS',
    iata: 'BOS',
    name: 'Boston Logan International Airport',
    city: 'Boston',
    country: 'United States',
    lat: 42.3656,
    lng: -71.0096,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'BNA',
    iata: 'BNA',
    name: 'Nashville International Airport',
    city: 'Nashville',
    country: 'United States',
    lat: 36.1245,
    lng: -86.6782,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'BTV',
    iata: 'BTV',
    name: 'Burlington International Airport',
    city: 'Burlington',
    country: 'United States',
    lat: 44.4719,
    lng: -73.1533,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'BWI',
    iata: 'BWI',
    name: 'Baltimore/Washington International Thurgood Marshall Airport',
    city: 'Baltimore',
    country: 'United States',
    lat: 39.1754,
    lng: -76.6684,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'CHS',
    iata: 'CHS',
    name: 'Charleston International Airport',
    city: 'Charleston',
    country: 'United States',
    lat: 32.8986,
    lng: -80.0405,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'CLT',
    iata: 'CLT',
    name: 'Charlotte Douglas International Airport',
    city: 'Charlotte',
    country: 'United States',
    lat: 35.2144,
    lng: -80.9473,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'CMH',
    iata: 'CMH',
    name: 'John Glenn Columbus International Airport',
    city: 'Columbus',
    country: 'United States',
    lat: 39.998,
    lng: -82.8919,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'CRW',
    iata: 'CRW',
    name: 'West Virginia International Yeager Airport',
    city: 'Charleston',
    country: 'United States',
    lat: 38.3731,
    lng: -81.5932,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'DEN',
    iata: 'DEN',
    name: 'Denver International Airport',
    city: 'Denver',
    country: 'United States',
    lat: 39.8561,
    lng: -104.6737,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'DSM',
    iata: 'DSM',
    name: 'Des Moines International Airport',
    city: 'Des Moines',
    country: 'United States',
    lat: 41.534,
    lng: -93.6631,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'DTW',
    iata: 'DTW',
    name: 'Detroit Metropolitan Wayne County Airport',
    city: 'Detroit',
    country: 'United States',
    lat: 42.2162,
    lng: -83.3554,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'DFW',
    iata: 'DFW',
    name: 'Dallas/Fort Worth International Airport',
    city: 'Dallas-Fort Worth',
    country: 'United States',
    lat: 32.8998,
    lng: -97.0403,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'EWR',
    iata: 'EWR',
    name: 'Newark Liberty International Airport',
    city: 'Newark',
    country: 'United States',
    lat: 40.6895,
    lng: -74.1745,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'FAR',
    iata: 'FAR',
    name: 'Hector International Airport',
    city: 'Fargo',
    country: 'United States',
    lat: 46.9207,
    lng: -96.8158,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'FSD',
    iata: 'FSD',
    name: 'Sioux Falls Regional Airport',
    city: 'Sioux Falls',
    country: 'United States',
    lat: 43.582,
    lng: -96.7419,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'HNL',
    iata: 'HNL',
    name: 'Daniel K. Inouye International Airport',
    city: 'Honolulu',
    country: 'United States',
    lat: 21.3245,
    lng: -157.9251,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'IAD',
    iata: 'IAD',
    name: 'Washington Dulles International Airport',
    city: 'Washington',
    country: 'United States',
    lat: 38.9531,
    lng: -77.4565,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'ICT',
    iata: 'ICT',
    name: 'Wichita Dwight D. Eisenhower National Airport',
    city: 'Wichita',
    country: 'United States',
    lat: 37.6499,
    lng: -97.4331,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'ILG',
    iata: 'ILG',
    name: 'Wilmington Airport',
    city: 'Wilmington',
    country: 'United States',
    lat: 39.6787,
    lng: -75.6065,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'IND',
    iata: 'IND',
    name: 'Indianapolis International Airport',
    city: 'Indianapolis',
    country: 'United States',
    lat: 39.7173,
    lng: -86.2944,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'JAN',
    iata: 'JAN',
    name: 'Jackson-Medgar Wiley Evers International Airport',
    city: 'Jackson',
    country: 'United States',
    lat: 32.3112,
    lng: -90.0759,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'JAC',
    iata: 'JAC',
    name: 'Jackson Hole Airport',
    city: 'Jackson',
    country: 'United States',
    lat: 43.6073,
    lng: -110.7377,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'JFK',
    iata: 'JFK',
    name: 'John F. Kennedy International Airport',
    city: 'New York',
    country: 'United States',
    lat: 40.6413,
    lng: -73.7781,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'LAS',
    iata: 'LAS',
    name: 'Harry Reid International Airport',
    city: 'Las Vegas',
    country: 'United States',
    lat: 36.084,
    lng: -115.1537,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'LAX',
    iata: 'LAX',
    name: 'Los Angeles International Airport',
    city: 'Los Angeles',
    country: 'United States',
    lat: 33.9416,
    lng: -118.4085,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'MHT',
    iata: 'MHT',
    name: 'Manchester-Boston Regional Airport',
    city: 'Manchester',
    country: 'United States',
    lat: 42.9326,
    lng: -71.4357,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'MIA',
    iata: 'MIA',
    name: 'Miami International Airport',
    city: 'Miami',
    country: 'United States',
    lat: 25.7959,
    lng: -80.287,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'MKE',
    iata: 'MKE',
    name: 'Milwaukee Mitchell International Airport',
    city: 'Milwaukee',
    country: 'United States',
    lat: 42.9472,
    lng: -87.8966,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'MSP',
    iata: 'MSP',
    name: 'Minneapolis-Saint Paul International Airport',
    city: 'Minneapolis-Saint Paul',
    country: 'United States',
    lat: 44.8848,
    lng: -93.2223,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'MSY',
    iata: 'MSY',
    name: 'Louis Armstrong New Orleans International Airport',
    city: 'New Orleans',
    country: 'United States',
    lat: 29.9934,
    lng: -90.258,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'OKC',
    iata: 'OKC',
    name: 'Will Rogers World Airport',
    city: 'Oklahoma City',
    country: 'United States',
    lat: 35.3931,
    lng: -97.6007,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'OMA',
    iata: 'OMA',
    name: 'Eppley Airfield',
    city: 'Omaha',
    country: 'United States',
    lat: 41.3032,
    lng: -95.8941,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'ORD',
    iata: 'ORD',
    name: "O'Hare International Airport",
    city: 'Chicago',
    country: 'United States',
    lat: 41.9742,
    lng: -87.9073,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'PDX',
    iata: 'PDX',
    name: 'Portland International Airport',
    city: 'Portland',
    country: 'United States',
    lat: 45.5898,
    lng: -122.5951,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'PHL',
    iata: 'PHL',
    name: 'Philadelphia International Airport',
    city: 'Philadelphia',
    country: 'United States',
    lat: 39.8744,
    lng: -75.2424,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'PHX',
    iata: 'PHX',
    name: 'Phoenix Sky Harbor International Airport',
    city: 'Phoenix',
    country: 'United States',
    lat: 33.4342,
    lng: -112.0116,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'PVD',
    iata: 'PVD',
    name: 'Rhode Island T. F. Green International Airport',
    city: 'Providence',
    country: 'United States',
    lat: 41.7326,
    lng: -71.4204,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'PWM',
    iata: 'PWM',
    name: 'Portland International Jetport',
    city: 'Portland',
    country: 'United States',
    lat: 43.6462,
    lng: -70.3093,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'SDF',
    iata: 'SDF',
    name: 'Louisville Muhammad Ali International Airport',
    city: 'Louisville',
    country: 'United States',
    lat: 38.1744,
    lng: -85.736,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'SEA',
    iata: 'SEA',
    name: 'Seattle-Tacoma International Airport',
    city: 'Seattle',
    country: 'United States',
    lat: 47.4502,
    lng: -122.3088,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'SLC',
    iata: 'SLC',
    name: 'Salt Lake City International Airport',
    city: 'Salt Lake City',
    country: 'United States',
    lat: 40.7899,
    lng: -111.9791,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'STL',
    iata: 'STL',
    name: 'St. Louis Lambert International Airport',
    city: 'St. Louis',
    country: 'United States',
    lat: 38.7487,
    lng: -90.37,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'XNA',
    iata: 'XNA',
    name: 'Northwest Arkansas National Airport',
    city: 'Bentonville',
    country: 'United States',
    lat: 36.2819,
    lng: -94.3068,
    size: 'large',
    basePrice: 300000
  }),

  Object.freeze({
    id: 'ABQ',
    iata: 'ABQ',
    name: 'Albuquerque International Sunport',
    city: 'Albuquerque',
    country: 'United States',
    lat: 35.0402,
    lng: -106.609,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'CDG',
    iata: 'CDG',
    name: 'Charles de Gaulle Airport',
    city: 'Paris',
    country: 'France',
    lat: 49.0097,
    lng: 2.5479,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'CPT',
    iata: 'CPT',
    name: 'Cape Town International Airport',
    city: 'Cape Town',
    country: 'South Africa',
    lat: -33.9696,
    lng: 18.5972,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'DEL',
    iata: 'DEL',
    name: 'Indira Gandhi International Airport',
    city: 'Delhi',
    country: 'India',
    lat: 28.5562,
    lng: 77.1,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'DUB',
    iata: 'DUB',
    name: 'Dublin Airport',
    city: 'Dublin',
    country: 'Ireland',
    lat: 53.4213,
    lng: -6.2701,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'DXB',
    iata: 'DXB',
    name: 'Dubai International Airport',
    city: 'Dubai',
    country: 'United Arab Emirates',
    lat: 25.2532,
    lng: 55.3657,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'EZE',
    iata: 'EZE',
    name: 'Ministro Pistarini International Airport',
    city: 'Buenos Aires',
    country: 'Argentina',
    lat: -34.8222,
    lng: -58.5358,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'FCO',
    iata: 'FCO',
    name: 'Leonardo da Vinci International Airport',
    city: 'Rome',
    country: 'Italy',
    lat: 41.8003,
    lng: 12.2389,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'FRA',
    iata: 'FRA',
    name: 'Frankfurt Airport',
    city: 'Frankfurt',
    country: 'Germany',
    lat: 50.0379,
    lng: 8.5622,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'GRU',
    iata: 'GRU',
    name: 'Sao Paulo/Guarulhos International Airport',
    city: 'Sao Paulo',
    country: 'Brazil',
    lat: -23.4356,
    lng: -46.4731,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'GVA',
    iata: 'GVA',
    name: 'Geneva Airport',
    city: 'Geneva',
    country: 'Switzerland',
    lat: 46.2381,
    lng: 6.1089,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'HND',
    iata: 'HND',
    name: 'Tokyo Haneda Airport',
    city: 'Tokyo',
    country: 'Japan',
    lat: 35.5494,
    lng: 139.7798,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'ICN',
    iata: 'ICN',
    name: 'Incheon International Airport',
    city: 'Seoul',
    country: 'South Korea',
    lat: 37.4602,
    lng: 126.4407,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'JNB',
    iata: 'JNB',
    name: 'O. R. Tambo International Airport',
    city: 'Johannesburg',
    country: 'South Africa',
    lat: -26.1337,
    lng: 28.242,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'KUL',
    iata: 'KUL',
    name: 'Kuala Lumpur International Airport',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    lat: 2.7456,
    lng: 101.7072,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'LHR',
    iata: 'LHR',
    name: 'Heathrow Airport',
    city: 'London',
    country: 'United Kingdom',
    lat: 51.47,
    lng: -0.4543,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'LIS',
    iata: 'LIS',
    name: 'Humberto Delgado Airport',
    city: 'Lisbon',
    country: 'Portugal',
    lat: 38.7742,
    lng: -9.1342,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'MAD',
    iata: 'MAD',
    name: 'Adolfo Suarez Madrid-Barajas Airport',
    city: 'Madrid',
    country: 'Spain',
    lat: 40.4983,
    lng: -3.5676,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'MEX',
    iata: 'MEX',
    name: 'Mexico City International Airport',
    city: 'Mexico City',
    country: 'Mexico',
    lat: 19.4361,
    lng: -99.0719,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'NBO',
    iata: 'NBO',
    name: 'Jomo Kenyatta International Airport',
    city: 'Nairobi',
    country: 'Kenya',
    lat: -1.3192,
    lng: 36.9278,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'PEK',
    iata: 'PEK',
    name: 'Beijing Capital International Airport',
    city: 'Beijing',
    country: 'China',
    lat: 40.0799,
    lng: 116.6031,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'PER',
    iata: 'PER',
    name: 'Perth Airport',
    city: 'Perth',
    country: 'Australia',
    lat: -31.9403,
    lng: 115.9672,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'SCL',
    iata: 'SCL',
    name: 'Arturo Merino Benitez International Airport',
    city: 'Santiago',
    country: 'Chile',
    lat: -33.3929,
    lng: -70.7858,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'SIN',
    iata: 'SIN',
    name: 'Singapore Changi Airport',
    city: 'Singapore',
    country: 'Singapore',
    lat: 1.3644,
    lng: 103.9915,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'SYD',
    iata: 'SYD',
    name: 'Sydney Kingsford Smith Airport',
    city: 'Sydney',
    country: 'Australia',
    lat: -33.9399,
    lng: 151.1753,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'VIE',
    iata: 'VIE',
    name: 'Vienna International Airport',
    city: 'Vienna',
    country: 'Austria',
    lat: 48.1103,
    lng: 16.5697,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'WLG',
    iata: 'WLG',
    name: 'Wellington International Airport',
    city: 'Wellington',
    country: 'New Zealand',
    lat: -41.3272,
    lng: 174.805,
    size: 'large',
    basePrice: 300000
  }),
  Object.freeze({
    id: 'ZRH',
    iata: 'ZRH',
    name: 'Zurich Airport',
    city: 'Zurich',
    country: 'Switzerland',
    lat: 47.4581,
    lng: 8.5555,
    size: 'large',
    basePrice: 300000
  })
]);

module.exports = {
  AIRPORT_CATALOG
};
